.class public Lorg/adaway/util/Constants;
.super Ljava/lang/Object;
.source "Constants.java"


# static fields
.field public static final ANDROID_DATA_DATA_HOSTS:Ljava/lang/String; = null

.field public static final ANDROID_SYSTEM_ETC_HOSTS:Ljava/lang/String; = null

.field public static final ANDROID_SYSTEM_PATH:Ljava/lang/String; = null

.field public static final BOGUS_IPv4:Ljava/lang/String; = "0.0.0.0"

.field public static final COMMAND_CHMOD_644:Ljava/lang/String; = "chmod 644"

.field public static final COMMAND_CHMOD_666:Ljava/lang/String; = "chmod 666"

.field public static final COMMAND_CHOWN:Ljava/lang/String; = "chown 0:0"

.field public static final COMMAND_LN:Ljava/lang/String; = "ln -s"

.field public static final COMMAND_MKDIR:Ljava/lang/String; = "mkdir -p"

.field public static final COMMAND_RM:Ljava/lang/String; = "rm -f"

.field public static DEBUG:Z = false

.field public static final DEBUG_DISABLE_ROOT_CHECK:Z = false

.field public static final DEBUG_UPDATE_CHECK_SERVICE:Z = false

.field public static final DOWNLOADED_HOSTS_FILENAME:Ljava/lang/String; = "hosts_downloaded"

.field public static final FILE_SEPERATOR:Ljava/lang/String; = null

.field public static final HEADER1:Ljava/lang/String; = "# This hosts file is generated by AdAway."

.field public static final HEADER2:Ljava/lang/String; = "# Please do not modify it directly, it will be overwritten when AdAway is applied again."

.field public static final HEADER_EXPORT:Ljava/lang/String; = "# This hosts file contains exported entries from AdAway."

.field public static final HEADER_SOURCES:Ljava/lang/String; = "# This file is generated from the following sources:"

.field public static final HOSTS_FILENAME:Ljava/lang/String; = "hosts"

.field public static final LINE_SEPERATOR:Ljava/lang/String; = null

.field public static final LOCALHOST_HOSTNAME:Ljava/lang/String; = "localhost"

.field public static final LOCALHOST_IPv4:Ljava/lang/String; = "127.0.0.1"

.field public static final LOCALHOST_IPv6:Ljava/lang/String; = "::1"

.field public static final PREFS_NAME:Ljava/lang/String; = "preferences"

.field public static final TAG:Ljava/lang/String; = "AdAway"

.field public static final TCPDUMP_EXECUTEABLE:Ljava/lang/String; = "tcpdump"

.field public static final TCPDUMP_LOG:Ljava/lang/String; = "dns_log.txt"

.field public static final WEBSERVER_EXECUTEABLE:Ljava/lang/String; = "blank_webserver"

.field public static final WHITELIST_ENTRY:Ljava/lang/String; = "white"


# direct methods
.method static constructor <clinit>()V
    .locals 2

    .prologue
    .line 42
    const-string v0, "line.separator"

    const-string v1, "\n"

    invoke-static {v0, v1}, Ljava/lang/System;->getProperty(Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;

    move-result-object v0

    sput-object v0, Lorg/adaway/util/Constants;->LINE_SEPERATOR:Ljava/lang/String;

    .line 43
    const-string v0, "file.separator"

    const-string v1, "/"

    invoke-static {v0, v1}, Ljava/lang/System;->getProperty(Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;

    move-result-object v0

    sput-object v0, Lorg/adaway/util/Constants;->FILE_SEPERATOR:Ljava/lang/String;

    .line 57
    const-string v0, "java.home"

    const-string v1, "/system"

    invoke-static {v0, v1}, Ljava/lang/System;->getProperty(Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;

    move-result-object v0

    sput-object v0, Lorg/adaway/util/Constants;->ANDROID_SYSTEM_PATH:Ljava/lang/String;

    .line 58
    new-instance v0, Ljava/lang/StringBuilder;

    invoke-direct {v0}, Ljava/lang/StringBuilder;-><init>()V

    sget-object v1, Lorg/adaway/util/Constants;->ANDROID_SYSTEM_PATH:Ljava/lang/String;

    invoke-virtual {v0, v1}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;

    move-result-object v0

    sget-object v1, Lorg/adaway/util/Constants;->FILE_SEPERATOR:Ljava/lang/String;

    invoke-virtual {v0, v1}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;

    move-result-object v0

    const-string v1, "etc"

    invoke-virtual {v0, v1}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;

    move-result-object v0

    sget-object v1, Lorg/adaway/util/Constants;->FILE_SEPERATOR:Ljava/lang/String;

    invoke-virtual {v0, v1}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;

    move-result-object v0

    const-string v1, "hosts"

    invoke-virtual {v0, v1}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;

    move-result-object v0

    invoke-virtual {v0}, Ljava/lang/StringBuilder;->toString()Ljava/lang/String;

    move-result-object v0

    sput-object v0, Lorg/adaway/util/Constants;->ANDROID_SYSTEM_ETC_HOSTS:Ljava/lang/String;

    .line 60
    new-instance v0, Ljava/lang/StringBuilder;

    invoke-direct {v0}, Ljava/lang/StringBuilder;-><init>()V

    sget-object v1, Lorg/adaway/util/Constants;->FILE_SEPERATOR:Ljava/lang/String;

    invoke-virtual {v0, v1}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;

    move-result-object v0

    const-string v1, "data"

    invoke-virtual {v0, v1}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;

    move-result-object v0

    sget-object v1, Lorg/adaway/util/Constants;->FILE_SEPERATOR:Ljava/lang/String;

    invoke-virtual {v0, v1}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;

    move-result-object v0

    const-string v1, "data"

    invoke-virtual {v0, v1}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;

    move-result-object v0

    sget-object v1, Lorg/adaway/util/Constants;->FILE_SEPERATOR:Ljava/lang/String;

    invoke-virtual {v0, v1}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;

    move-result-object v0

    const-string v1, "hosts"

    invoke-virtual {v0, v1}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;

    move-result-object v0

    invoke-virtual {v0}, Ljava/lang/StringBuilder;->toString()Ljava/lang/String;

    move-result-object v0

    sput-object v0, Lorg/adaway/util/Constants;->ANDROID_DATA_DATA_HOSTS:Ljava/lang/String;

    return-void
.end method

.method public constructor <init>()V
    .locals 0

    .prologue
    .line 23
    invoke-direct {p0}, Ljava/lang/Object;-><init>()V

    return-void
.end method
